language: go
go:
  - tip
before_install:
  - go get github.com/mattn/gom
script:
  - $HOME/gopath/bin/gom install
  - $HOME/gopath/bin/gom test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

deployment:
  release:
     tag: /v.*/
     commands:
     - go get github.com/mitchellh/gox
     - go get github.com/tcnksm/ghr
     - gox --osarch "linux/386 linux/amd64 darwin/amd64 windows/386 windows/amd64" -output "dist/{{.Dir}}_$(git tag -l | tail -1)_{{.OS}}_{{.Arch}}/{{.Dir}}"
     - bash script/zip-releases.sh
     - ghr -t $GITHUB_TOKEN  --replace `git describe --tags` pkg/
